allowBuilds:
  "@parcel/watcher": false
  "@prisma/client": false
  "@prisma/engines": false
  esbuild: false
  prisma: false
  sharp: true
  unrs-resolver: false
  vue-demi: false
overrides:
  '@hono/node-server@<1.19.13': '>=1.19.13'
  esbuild@<=0.24.2: '>=0.25.0'
