allowBuilds:
  "@nestjs/core": false
  "@parcel/watcher": false
  "@prisma/client": false
  "@prisma/engines": false
  "@swc/core": false
  cbor-extract: false
  esbuild: false
  prisma: false
  sharp: true
  unrs-resolver: false
  vue-demi: false

autoInstallPeers: true
