export interface TopicDefinition {
  label: string;
  description: string;
  keywords: string[];
}

export const TOPIC_CATALOG: TopicDefinition[] = [
  {
    label: "Technology",
    description: "Digital tech, software, hardware, emerging tech trends",
    keywords: [
      "technology",
      "tech",
      "software",
      "hardware",
      "digital",
      "gadget",
      "device",
      "computer",
    ],
  },
  {
    label: "Programming",
    description: "Coding, algorithms, languages, software projects",
    keywords: [
      "programming",
      "code",
      "coding",
      "algorithm",
      "developer",
      "debug",
      "function",
      "variable",
      "api",
      "framework",
    ],
  },
  {
    label: "Artificial Intelligence",
    description: "AI, machine learning, language models, AI applications",
    keywords: [
      "artificial intelligence",
      "ai",
      "machine learning",
      "deep learning",
      "neural network",
      "llm",
      "language model",
      "chatgpt",
      "automation",
    ],
  },
  {
    label: "Data Science",
    description: "Data analysis, statistics, visualization, big data",
    keywords: [
      "data science",
      "data analysis",
      "statistics",
      "visualization",
      "big data",
      "dataset",
      "analytics",
      "insight",
    ],
  },
  {
    label: "Cybersecurity",
    description: "Security, cyber attacks, defense, digital privacy",
    keywords: [
      "cybersecurity",
      "security",
      "hack",
      "attack",
      "privacy",
      "encryption",
      "firewall",
      "malware",
      "vulnerability",
    ],
  },
  {
    label: "Product Design",
    description: "Product design process, user research, MVP",
    keywords: [
      "product design",
      "mvp",
      "prototype",
      "user research",
      "design thinking",
      "product manager",
      "iteration",
    ],
  },
  {
    label: "UX/UI",
    description: "User experience, interface design, interaction design",
    keywords: [
      "ux",
      "ui",
      "user experience",
      "interface design",
      "interaction design",
      "usability",
      "wireframe",
      "mockup",
    ],
  },
  {
    label: "Marketing",
    description: "Advertising, media, marketing campaigns, branding",
    keywords: [
      "marketing",
      "advertising",
      "campaign",
      "brand",
      "social media",
      "seo",
      "content marketing",
      "promotion",
    ],
  },
  {
    label: "Business",
    description: "Business strategy, management, sales, operations",
    keywords: [
      "business",
      "strategy",
      "management",
      "sales",
      "operations",
      "revenue",
      "profit",
      "enterprise",
      "corporation",
    ],
  },
  {
    label: "Startups",
    description: "Startup, fundraising, product building, growth",
    keywords: [
      "startup",
      "fundraising",
      "venture capital",
      "pitch",
      "founder",
      "growth",
      "scale",
      "incubator",
      "accelerator",
    ],
  },
  {
    label: "Finance",
    description: "Personal finance, budgeting, credit, accounting",
    keywords: [
      "finance",
      "budget",
      "credit",
      "accounting",
      "money",
      "saving",
      "expense",
      "income",
      "debt",
    ],
  },
  {
    label: "Investing",
    description: "Stocks, real estate, crypto, risk management",
    keywords: [
      "investing",
      "stock",
      "real estate",
      "crypto",
      "portfolio",
      "dividend",
      "trading",
      "risk management",
      "asset",
    ],
  },
  {
    label: "Economics",
    description: "Macroeconomics, microeconomics, markets, economic cycles",
    keywords: [
      "economics",
      "macroeconomics",
      "microeconomics",
      "market",
      "inflation",
      "gdp",
      "supply",
      "demand",
      "trade",
    ],
  },
  {
    label: "Education",
    description: "Learning methods, teaching, study skills",
    keywords: [
      "education",
      "learning",
      "teaching",
      "study",
      "school",
      "curriculum",
      "academic",
      "student",
      "teacher",
    ],
  },
  {
    label: "Language Learning",
    description: "English and foreign language learning, listening, speaking, reading, writing",
    keywords: [
      "language learning",
      "english",
      "vocabulary",
      "grammar",
      "pronunciation",
      "fluency",
      "bilingual",
      "speaking",
      "listening",
    ],
  },
  {
    label: "Study Abroad",
    description: "Study abroad prep, applications, scholarships, student life",
    keywords: [
      "study abroad",
      "scholarship",
      "university",
      "application",
      "visa",
      "international student",
      "campus",
      "exchange",
    ],
  },
  {
    label: "Health",
    description: "Healthcare, common diseases, healthy lifestyle",
    keywords: [
      "health",
      "healthcare",
      "disease",
      "doctor",
      "medical",
      "wellness",
      "fitness",
      "exercise",
      "treatment",
    ],
  },
  {
    label: "Nutrition",
    description: "Diets, food, balanced nutrition",
    keywords: [
      "nutrition",
      "diet",
      "food",
      "calorie",
      "vitamin",
      "protein",
      "carbohydrate",
      "meal",
      "organic",
    ],
  },
  {
    label: "Psychology",
    description: "Psychology, emotions, stress, mental health",
    keywords: [
      "psychology",
      "mental health",
      "emotion",
      "stress",
      "anxiety",
      "depression",
      "therapy",
      "behavior",
      "mindset",
    ],
  },
  {
    label: "Sports",
    description: "Sports, training, techniques, competitions",
    keywords: [
      "sports",
      "training",
      "competition",
      "athlete",
      "game",
      "team",
      "tournament",
      "championship",
      "coach",
    ],
  },
  {
    label: "Yoga",
    description: "Yoga, meditation, breathing, flexibility and balance",
    keywords: [
      "yoga",
      "meditation",
      "breathing",
      "flexibility",
      "balance",
      "pose",
      "mindfulness",
      "stretch",
      "zen",
    ],
  },
  {
    label: "Cooking",
    description: "Recipes, kitchen tips, cuisine",
    keywords: [
      "cooking",
      "recipe",
      "kitchen",
      "cuisine",
      "chef",
      "baking",
      "ingredient",
      "meal prep",
      "food",
    ],
  },
  {
    label: "Travel",
    description: "Destinations, travel experiences, local culture",
    keywords: [
      "travel",
      "destination",
      "vacation",
      "trip",
      "adventure",
      "tourism",
      "backpack",
      "explore",
      "journey",
    ],
  },
  {
    label: "Culture",
    description: "Customs, festivals, cultural life",
    keywords: [
      "culture",
      "custom",
      "festival",
      "tradition",
      "heritage",
      "cultural",
      "celebration",
      "ritual",
      "diversity",
    ],
  },
  {
    label: "History",
    description: "Historical events, figures, timelines",
    keywords: [
      "history",
      "historical",
      "century",
      "war",
      "empire",
      "ancient",
      "civilization",
      "timeline",
      "event",
    ],
  },
  {
    label: "Music",
    description: "Songs, artists, music genres, music production",
    keywords: [
      "music",
      "song",
      "artist",
      "album",
      "genre",
      "melody",
      "rhythm",
      "instrument",
      "concert",
    ],
  },
  {
    label: "Film",
    description: "Cinema, film reviews, script analysis",
    keywords: [
      "film",
      "cinema",
      "movie",
      "director",
      "actor",
      "review",
      "screenplay",
      "scene",
      "hollywood",
    ],
  },
  {
    label: "Books",
    description: "Good books, book summaries, content discussion",
    keywords: [
      "book",
      "reading",
      "novel",
      "author",
      "literature",
      "chapter",
      "summary",
      "fiction",
      "nonfiction",
    ],
  },
  {
    label: "Art",
    description: "Painting, fine arts, creative art",
    keywords: [
      "art",
      "painting",
      "drawing",
      "sculpture",
      "creative",
      "gallery",
      "artist",
      "canvas",
      "abstract",
    ],
  },
  {
    label: "Photography",
    description: "Photography, photo techniques, post-processing, equipment",
    keywords: [
      "photography",
      "photo",
      "camera",
      "lens",
      "portrait",
      "landscape",
      "editing",
      "shutter",
      "aperture",
    ],
  },
  {
    label: "Fashion",
    description: "Style, fashion trends, outfit coordination",
    keywords: [
      "fashion",
      "style",
      "trend",
      "outfit",
      "clothing",
      "designer",
      "wardrobe",
      "accessory",
      "runway",
    ],
  },
  {
    label: "Beauty",
    description: "Skincare, makeup, body care",
    keywords: [
      "beauty",
      "skincare",
      "makeup",
      "cosmetic",
      "moisturizer",
      "serum",
      "routine",
      "glow",
      "balm",
    ],
  },
  {
    label: "Family",
    description: "Family life, relationships, home care",
    keywords: [
      "family",
      "relationship",
      "marriage",
      "parent",
      "sibling",
      "home",
      "household",
      "bond",
      "love",
    ],
  },
  {
    label: "Parenting",
    description: "Child-rearing, child education, parenting skills",
    keywords: [
      "parenting",
      "child",
      "baby",
      "toddler",
      "discipline",
      "nurture",
      "childcare",
      "mother",
      "father",
    ],
  },
  {
    label: "Environment",
    description: "Environmental protection, climate, sustainable development",
    keywords: [
      "environment",
      "climate",
      "sustainability",
      "pollution",
      "recycle",
      "green",
      "conservation",
      "ecosystem",
      "carbon",
    ],
  },
  {
    label: "News",
    description: "Current affairs, news updates, notable events",
    keywords: [
      "news",
      "current affairs",
      "headline",
      "breaking",
      "report",
      "update",
      "press",
      "media",
      "journalism",
    ],
  },
  {
    label: "Interviews",
    description: "People interviews, experience sharing, stories",
    keywords: [
      "interview",
      "conversation",
      "story",
      "experience",
      "podcast",
      "guest",
      "host",
      "discussion",
      "q&a",
    ],
  },
  {
    label: "Presentations",
    description: "Presentation skills, public speaking",
    keywords: [
      "presentation",
      "public speaking",
      "speech",
      "slide",
      "audience",
      "stage",
      "talk",
      "keynote",
      "pitch",
    ],
  },
  {
    label: "Soft Skills",
    description: "Communication, teamwork, professional skills",
    keywords: [
      "soft skills",
      "communication",
      "teamwork",
      "leadership",
      "collaboration",
      "negotiation",
      "empathy",
      "professional",
    ],
  },
  {
    label: "Time Management",
    description: "Planning, prioritization, productivity",
    keywords: [
      "time management",
      "planning",
      "prioritization",
      "productivity",
      "schedule",
      "deadline",
      "focus",
      "efficiency",
      "organization",
    ],
  },
  {
    label: "Self-Development",
    description: "Mindset, habits, goals, self-improvement",
    keywords: [
      "self development",
      "mindset",
      "habit",
      "goal",
      "improvement",
      "growth",
      "motivation",
      "discipline",
      "success",
    ],
  },
  {
    label: "Science",
    description: "Scientific discoveries, experiments, inventions",
    keywords: [
      "science",
      "discovery",
      "experiment",
      "research",
      "hypothesis",
      "theory",
      "invention",
      "laboratory",
      "scientific",
    ],
  },
  {
    label: "Mathematics",
    description: "Basic to advanced math, exercises, mathematical thinking",
    keywords: [
      "mathematics",
      "math",
      "equation",
      "calculation",
      "algebra",
      "geometry",
      "calculus",
      "number",
      "theorem",
    ],
  },
  {
    label: "Physics",
    description: "Physics concepts, experiments, applications",
    keywords: [
      "physics",
      "force",
      "energy",
      "motion",
      "gravity",
      "quantum",
      "particle",
      "relativity",
      "wave",
    ],
  },
  {
    label: "Biology",
    description: "Biology, ecosystems, living organisms",
    keywords: [
      "biology",
      "organism",
      "cell",
      "dna",
      "evolution",
      "species",
      "ecosystem",
      "gene",
      "life",
    ],
  },
  {
    label: "Chemistry",
    description: "Chemical reactions, substances, experiments",
    keywords: [
      "chemistry",
      "chemical",
      "reaction",
      "element",
      "compound",
      "molecule",
      "acid",
      "base",
      "experiment",
    ],
  },
  {
    label: "Geography",
    description: "Physical geography, human geography, maps",
    keywords: [
      "geography",
      "map",
      "continent",
      "country",
      "region",
      "terrain",
      "climate zone",
      "landscape",
      "location",
    ],
  },
  {
    label: "Politics",
    description: "Politics, public policy, governance",
    keywords: [
      "politics",
      "policy",
      "government",
      "election",
      "democracy",
      "legislation",
      "congress",
      "president",
      "campaign",
    ],
  },
  {
    label: "Law",
    description: "Law, rights and duties, regulations",
    keywords: [
      "law",
      "legal",
      "rights",
      "regulation",
      "court",
      "judge",
      "attorney",
      "constitution",
      "justice",
    ],
  },
  {
    label: "Society",
    description: "Social issues, community, social trends",
    keywords: [
      "society",
      "community",
      "social",
      "culture",
      "inequality",
      "diversity",
      "inclusion",
      "movement",
      "activism",
    ],
  },
  {
    label: "Other",
    description: "Topics not covered by the above categories",
    keywords: [],
  },
];
